### ISSUE TITLE
Functional Requirements and Use Cases

### ISSUE THREAD

**Issue by as3810t** [as3810t/COMPSEC-HW-GROTESQUE-GECKO#1]
[WIKI](https://github.com/as3810t/COMPSEC-HW-GROTESQUE-GECKO/wiki/Functional-Requirements-and-Use-Cases)

**Comment by as3810t** [comment]
@sarvaryk @futobarna Could you review to document whether you spot something we missed?

**Comment by futobarna** [comment]
Here are the things that @sarvaryk and me thought might need some change:
- FU2.1: Maybe users could use either email or username for logging in
- FU4.2.3: Administrators should only be able to initiate password resets
- FCo1: It should say: comment _on_ CAFFs

**Comment by as3810t** [comment]
I agree with you on FU4.2.3, however we should iterate on it a bit.

If the administrators can only initiate password resets (which is indeed necessary to avoid admins impersonating users), then a mechanism is needed which allows users to reset passwords with email? And preferably not a link, because we do not plan to develop a web client.

**Comment by as3810t** [comment]
Based on our meeting, I updated the list of user related functional requirements (**FU***), and the integrity related security requirements (**SI***).
