### ISSUE TITLE
Testing plan

### ISSUE THREAD

**Issue by as3810t** [as3810t/COMPSEC-HW-GROTESQUE-GECKO#10]

**Comment by as3810t** [comment]
I wrote some sections about the tools to be used for analysis: [Testing Tools](https://github.com/as3810t/COMPSEC-HW-GROTESQUE-GECKO/wiki/Testing-Tools)

This wiki page should possible be deleted, and its content integrated in the Testing Plan.

**Comment by sarvaryk** [comment]
@as3810t @futobarna 
@ZsAgnes and I wrote the testing plan. Could you review it?

**Comment by futobarna** [comment]
It makes good use of what's already on the wiki and summarizes it all well. I couldn't find any problems.

**Comment by as3810t** [comment]
I agree, I think it summarizes the documents nicely.
