### ISSUE TITLE
Ensuring Code Quality and Security

### ISSUE THREAD

**Issue by as3810t** [as3810t/COMPSEC-HW-GROTESQUE-GECKO#11]
These documents should address:
- Secure coding standards to use
- Checking compliance with secure coding standards
  - With static analysis
  - In IDE during development
- Quality gates, and how they are monitored, enforced.

**Comment by as3810t** [comment]
[Quality Gates](https://github.com/as3810t/COMPSEC-HW-GROTESQUE-GECKO/wiki/Quality-Gates)
[Secure Coding Standards and Checking Compliance](https://github.com/as3810t/COMPSEC-HW-GROTESQUE-GECKO/wiki/Secure-Coding-Standards-and-Checking-Compliance)
[Static Analysis](https://github.com/as3810t/COMPSEC-HW-GROTESQUE-GECKO/wiki/Static-Analysis)
[Enforcing Code Quality and Security](https://github.com/as3810t/COMPSEC-HW-GROTESQUE-GECKO/wiki/Enforcing-Code-Quality-and-Security)

**Comment by as3810t** [comment]
@sarvaryk @ZsAgnes @futobarna 
I'd like to request a review to check whether I missed something, or the documents contains an inconsistency.

**Comment by sarvaryk** [comment]
@as3810t :
@ZsAgnes and I checked the content of the document and we think it summarizes the used GitHub features quiet nicely.

**Comment by futobarna** [comment]
I also think this is a good summary and didn't find any problems with it.
