### ISSUE TITLE
Security Requirements and Goals

### ISSUE THREAD

**Issue by as3810t** [as3810t/COMPSEC-HW-GROTESQUE-GECKO#2]
[WIKI](https://github.com/as3810t/COMPSEC-HW-GROTESQUE-GECKO/wiki/Security-Requirements-and-Goals)

**Comment by as3810t** [comment]
@sarvaryk @futobarna Could you review the document whether you spot something we missed?

**Comment by futobarna** [comment]
Here are the things that @sarvaryk and me thought might need some change:
- Which part of the system contains the comments? (we assumed CAFF data)
- SI4: Missing "e" in email

**Comment by as3810t** [comment]
Based on our meeting, I updated the list of user related functional requirements (FU4*), and the integrity related security requirements (SI4*).

@sarvaryk or @futobarna Could one of you check if this matches what we agreed upon?

**Comment by sarvaryk** [comment]
The changes are now correctly reflected in the requirements.
In my opinion the issue can be closed.
