### ISSUE TITLE
Threat Assessment

### ISSUE THREAD

**Issue by as3810t** [as3810t/COMPSEC-HW-GROTESQUE-GECKO#3]
[WIKI](https://github.com/as3810t/COMPSEC-HW-GROTESQUE-GECKO/wiki/Threat-Assessment)

**Comment by futobarna** [comment]
@ZsAgnes @as3810t Could you review the page to make sure we haven't missing anything important

**Comment by as3810t** [comment]
Regarding the dataflow map, I have the following remarks:

- You denoted the data stores with dashed rectangles, although the slides denote it with rectangles only with horizontal sides. We achieved it by using a Partial Rectangle (Basic category) rotated by 90 degrees and grouped with a text box.
- The user data action is not logged.
- It is a personal nitpick, but I would decentralize the logging facilities, and allow the Log data manager to communicate directly with the Authentication, User data manager and CAFF data manager components instead of using the Server to mediate the logs. It would be more future-proof.

Otherwise I think it is top notch!

**Comment by sarvaryk** [comment]
In correspondence to our meeting, I corrected the first two findings.

**Comment by as3810t** [comment]
Based on our meeting, I updated the list of user related functional requirements (FU4.2*), and the integrity related security requirements (SI4*).

The *Threat model* should be updated accordingly, and then the issue can be closed.

**Comment by sarvaryk** [comment]
The changes are now also reflected in the updated version of the threat model.
