### ISSUE TITLE
Structural Model of the System

### ISSUE THREAD

**Issue by as3810t** [as3810t/COMPSEC-HW-GROTESQUE-GECKO#5]
[WIKI](https://github.com/as3810t/COMPSEC-HW-GROTESQUE-GECKO/wiki/Structural-Model-of-the-System)

**Comment by futobarna** [comment]
@as3810t and I have made the diagram, and I wrote the documentation for it.
@ZsAgnes @sarvaryk could you check if there are any mistakes or unclear phrasing and see if there's anything missing?

**Comment by sarvaryk** [comment]
I think it gives a nice and brief overview about the systems structure. Maybe some words about the Crypto service could be useful and maybe some clarification if "CAFF modification: The interface used for modifying CAFF files." means the modification of the CAFF file itself or just its metadata.

**Comment by futobarna** [comment]
I edited the page based on your feedback.

**Comment by as3810t** [comment]
I think a port (and related sequence diagram) is missing for CAFF deletion.

**Comment by futobarna** [comment]
Page now includes CAFF delete.
