### ISSUE TITLE
Behavioral Model of the System

### ISSUE THREAD

**Issue by as3810t** [as3810t/COMPSEC-HW-GROTESQUE-GECKO#6]
[WIKI](https://github.com/as3810t/COMPSEC-HW-GROTESQUE-GECKO/wiki/Behavioral-Model-of-the-System)

**Comment by sarvaryk** [comment]
The only thing I found was, that at the Log query scenario the starting "The" should be corrected to "To". Otherwise it's spot on!

**Comment by ZsAgnes** [comment]
I have read it and in my opinion it is a nicely written document.
